### ISSUE TITLE
Add skylint

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_typescript#109]
When syncing a contributed PR into google-internal repo, the skylark linter runs. That means I have to clean up the code from contributors.

Instead we should run the skylint tool as part of the circleCI build on this repo so that PRs are already clean by the time I try to merge them.

Note that due to https://github.com/bazelbuild/bazel/issues/4086 we have to clone the entire bazel repo (maybe just fetch a release `.tgz` so we don't fetch all the git history and metadata)

To avoid version skew, rather than have individual engineers follow manual instructions to install a global version of skylint across their projects, we should build and run it from a `WORKSPACE` reference. See similar setup for running the buildifier tool:

`yarn buildifier`: https://github.com/angular/angular/blob/f593552cfe44ced74a3ec7e95a9ae847094fb632/package.json#L19
relies on fetching that repo in `WORKSPACE`:
https://github.com/angular/angular/blob/f593552cfe44ced74a3ec7e95a9ae847094fb632/WORKSPACE#L36-L43
This runs the tool across all sources in developer's clone.

For CI, to avoid the lag of building the tool from head (at least until we have a remote cache in circleCI) I pre-build the binary in the docker image:
https://github.com/alexeagle/ngcontainer/blob/e4c226795cdbf0069675a52e399c6cbbae441f66/Dockerfile#L37-L46
so we should probably do the same thing so that buildifier and skylint have the same setup.

**Comment by alexeagle** [comment]
@mrmeku I think this is not finished yet, because there is no enforcement on the CI?

**Comment by mrmeku** [comment]
Yeah, you're right. Sorry about that!

**Comment by alexeagle** [comment]
No, oops, it's my fault, I left https://github.com/bazelbuild/rules_typescript/pull/113 open.
