### ISSUE TITLE
Add a devserver example that uses node_modules

### ISSUE THREAD

**Issue by appsforartists** [bazelbuild/rules_typescript#126]
It's a very common workflow to import external open-source modules into a project being served by a devserver; therefore, the example should include it.  Specifically, we should document whatever needs to be done in `ts_library` to make `ts_devserver` concat-and-serve `node_modules`.

According to the NPM homepage, `lodash` and `react` are 2 of the most depended-upon packages.  At least one of them should be used in an example.  Plus, both have external typings, so they would also showcase the need to include `@types/react` alongside `react` (#125).

Related: #103

**Comment by alexeagle** [comment]
Let's use #103 for this.
