### ISSUE TITLE
ts_web_test should serve static files

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_typescript#131]
Some tests need karma to be configured such that static files (e.g some JSON data) can be served with a window.fetch.
For example, Angular has some disabled tests (`tags = ["manual"]`) because this isn't available.

The obvious design is to be similar to `ts_devserver` to keep a simple mental model for users. Accept the `data[]` attribute and serve anything in data, relative to the package where the rule appears.

**Comment by alexeagle** [comment]
@jelbourn would like this as well, so that angular components with `templateUrl` could use JIT compiler under ts_web_test

**Comment by gregmagolan** [comment]
I think it should also allow for additional_root_paths as ts_devserver handles in #177

**Comment by gregmagolan** [comment]
Resolved with #209 (https://github.com/bazelbuild/rules_typescript/commit/80ce606dcb0076378629cc34d96852302d17f8ce)
