### ISSUE TITLE
Using rules_typescript in package.json vs git_repository in WORKSPACE

### ISSUE THREAD

**Issue by yohcop** [bazelbuild/rules_typescript#135]
Hi,

This is more a clarification question. The README suggests to "Include @bazel/typescript in package.json#devDependencies", followed by, in WORKSPACE:
```
local_repository(
    name = "build_bazel_rules_typescript",
    path = "node_modules/@bazel/typescript",
)
```

On the other hand, @alexeagle 's angular [example repo](https://github.com/alexeagle/angular-bazel-example) just uses in the WORKSPACE file:
```
git_repository(
    name = "build_bazel_rules_typescript",
    remote = "https://github.com/bazelbuild/rules_typescript.git",
    tag = "b94f18bcdbf529615b57bf24de773758c33d85fc",
)
```

Does it matter which one is used? Does the first one actually not create a bootstraping issue, where the WORKSPACE file would be invalid until `bazel run @yarn//:yarn` is run, since the local repository doesn't exist - but an invalid WORKSPACE file prevents the bazel run?

**Comment by alexeagle** [comment]
Right now, there is nothing to be gained from fetching `@bazel/typescript` from npm, and I have not been updating the package. The README is wrong.
However, I think we should use npm for versioning instead. I started a design for this over the holidays but lost it. It's not related to bootstrapping, rather it's just that npm has better semantics like peerDependencies to express version ranges that are compatible.

**Comment by yohcop** [comment]
This is just my 2c, not a strong opinion. I prefer versioning in the WORKSPACE directory, for what is bazel-related at least. I thought it was a bit odd to have to put this in my package.json file when it's a bazel tool. Given dependencies of rules_typescript should not leak outside (as far as I remember, it now uses its own node_modules right?), I don't know if we would need things like peerDependencies. But maybe I'm missing the bigger picture...

**Comment by alexeagle** [comment]
What if you want to get a bugfix from typescript? If the ts_library rule
only ever runs ts@x.y.z, there is no way for a user to use ts@x.y.z+1

I agree that it's nice for the toolchain to be self-contained and not rely
on anything in your node_modules directory. But then you also have the
problem that your editor uses the TS version in node_modules and the
ts_library rule uses a different version, and gives different results.

I'd be happy to schedule some design time to think through this more, I
haven't convinced myself what is the right answer yet...

**Comment by alexeagle** [comment]
FYI `@bazel/typescript` on NPM is now up-to-date again. NPM supports transitive dependencies, so users of the `@angular/bazel` package get the correct version of `@bazel/typescript` rather than futzing around in the `WORKSPACE` file.
Still planning to keep both options.

**Comment by yohcop** [comment]
Hi again,

I agree with your points, maybe it would be nicer. But bootstraping doesn't work the way it's described in the README right now as far as I can tell. When I don't have yet a node_modules directory (e.g. in CI)

```
local_repository(
    name = "build_bazel_rules_typescript",
    path = "node_modules/@bazel/typescript",
)
```

I have a problem when trying to run yarn to install rules_typescript.
Baze fails when reading the WORKSPACE I assume:

```
> bazel run @nodejs//:yarn
ERROR: error loading package '': Encountered error while reading extension
 file 'defs.bzl': no such package '@build_bazel_rules_typescript//': /home/y/.cache/bazel/_bazel_y/353cc7731d9fb1ef948c81259e5d7654/external/build_bazel_rules_typescript must be an existing directory
```

So this seems to be a bit of a chicken and egg problem. `node_modules/@bazel/typescript/` doesn't exist, and it's supposed to be created by `bazel run @nodejs//:yarn`, which needs it to run.

I've looked at https://github.com/alexeagle/angular-bazel-example/blob/master/WORKSPACE and it also uses the http archive for this repo instead of the npm version.

I'm pretty sure this is nothing new, but maybe worth mentioning somewhere?

**Comment by jfaust** [comment]
This is something I've just run into as well - it seems like it's impossible to use `@nodejs//:yarn` correctly with these rules.

**Comment by gregmagolan** [comment]
Update on this. We've landed idiomatic install for rule_typescript so the npm `@bazel/typescript` package is now a .js only distribution and it contains the .js files used by the rules_typescript rules as well as listing their npm dependencies. The bazel rules themselves must now be pulled via http_archive (or git_repository).

See https://github.com/bazelbuild/rules_typescript#installation, or take a look at https://github.com/alexeagle/angular-bazel-example which shows to build with an Angular app with the latest rules_typescript. Note: in angular-bazel-example, the build_bazel_rules_typescript archive is downloaded in the `rules_angular_dependencies()` which comes from the Angular rules which ensures that the appropriate version is downloaded by default.
