### ISSUE TITLE
Allow Typescript files/directories live in a subdirectory?

### ISSUE THREAD

**Issue by zombiezen** [bazelbuild/rules_typescript#14]
I have a project I'm building where I would like to place the Typescript files and Typescript configs (package.json and tsconfig.json) in a subdirectory of my workspace.  AFAICT, this doesn't seem to be supported by these rules.  Can you add docs or support for this? Thanks!

**Comment by yohcop** [comment]
I have my files/configs in a subdirectory, and it works just fine... What
seems to be your issue?

**Comment by zombiezen** [comment]
I was experiencing an issue with node_modules not being present (I think?).  The docs just aren't very clear if this works or not, since node_modules isn't explicitly mentioned by label.

**Comment by yohcop** [comment]
Ah, that's true actually. it appears to work for me, maybe because i have tsconfig.json in the same directory as node_modules:
in sub/dir/BUILD, i have:
```
exports_files(["tsconfig.json"])
# NOTE: this will move to node_modules/BUILD in a later release
filegroup(name = "node_modules", srcs = glob(["node_modules/**/*"]))
```
then, in sub/dir/lib/BUILD:
```
ts_library(
    name = "lib",
    srcs = [
      "actions.ts",
      "reducer.ts",
    ],
    deps = [...],
    module_name = "sub/dir/lib",
    tsconfig = "//sub/dir:tsconfig.json",
)
```
But true, there is no reference to `//sub/dir:node_modules`

**Comment by alexeagle** [comment]
Two separate things:
- any node program (eg. the typescript compiler) expects to find a label `//:node_modules` so you need to have a `BUILD` or `BUILD.bazel` file in the project root (next to the `WORKSPACE`) that contains the `filegroup`
- separately, your rules point to a location where your `tsconfig.json` lives. That can be anywhere, but in order to reference it, you need a `BUILD` or `BUILD.bazel` in a directory containing `tsconfig.json` that has the `exports_files`. For example:

`subdir/tsconfig.json`: `{ ... }`
`subdir/BUILD.bazel`: ```
exports_files(["tsconfig.json"])
ts_library(tsconfig = ":tsconfig.json")
```

I can change the example to express this degree of freedom.

**Comment by alittletina** [comment]
if all node programs expect a `//:node_modules`, does this mean that all node libraries and programs (and typescript libraries / programs) will all use a single, shared `node_modules` directory to resolve dependencies?

how do i get two independent cli tools to `yarn install` their `package.json`s and use their own separate node_modules folder?

**Comment by alexeagle** [comment]
you can have a single `//:node_modules` or multiple. Internally at google, we actually have a separate rule for every node module, then we have to declare dependencies on each one.

Here's an example:
https://github.com/bazelbuild/rules_nodejs/blob/master/WORKSPACE#L30
when you `bazel run @yarn//:yarn` it will install dependencies for the two examples independently.
Then each node-related rule uses its `node_modules` attribute to point to the ones it wants:
https://github.com/bazelbuild/rules_nodejs/blob/master/examples/rollup/BUILD.bazel#L32

In theory you could have many separate `filegroup`s, like `node_modules_for_use_case1`, `node_modules_for_use_case2` and then each use case references a different one.
