### ISSUE TITLE
no such package '@build_bazel_rules_typescript_tsc_wrapped_deps//':

### ISSUE THREAD

**Issue by acehko** [bazelbuild/rules_typescript#142]
I have set up a repository to test the typescript rules here: [https://github.com/acehko/bazel_typescript_test](https://github.com/acehko/bazel_typescript_test).

When I try to build I get this error.

Install node modules:
```bash
bazel run @yarn//:yarn 
INFO: Analysed target @yarn//:yarn (0 packages loaded).
INFO: Found 1 target...
Target @yarn//:yarn up-to-date:
  bazel-bin/external/yarn/yarn
INFO: Elapsed time: 0.105s, Critical Path: 0.01s
INFO: Build completed successfully, 1 total action

INFO: Running command line: bazel-bin/external/yarn/yarn
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 0.12s.
```

Build:
```bash
bazel build //:lib                                                                                                                                               ~/code/typescript/bazel_typescript_test
ERROR: /home/andrija/code/typescript/bazel_typescript_test/BUILD.bazel:10:1: every rule of type ts_library implicitly depends upon the target '@build_bazel_rules_typescript_tsc_wrapped_deps//:node_modules', but this target could not be found because of: no such package '@build_bazel_rules_typescript_tsc_wrapped_deps//': npm_install failed:  (Process terminated by signal 6)
ERROR: Analysis of target '//:lib' failed; build aborted: no such package '@build_bazel_rules_typescript_tsc_wrapped_deps//': npm_install failed:  (Process terminated by signal 6)
INFO: Elapsed time: 2.431s
FAILED: Build did NOT complete successfully (1 packages loaded)
```

**Comment by alexeagle** [comment]
You need to call `ts_setup_workspace` from your `WORKSPACE` file, see the readme.

**Comment by acehko** [comment]
It is called here: https://github.com/acehko/bazel_typescript_test/blob/master/WORKSPACE#L19.
I copied the example from [here](https://github.com/alexeagle/angular-bazel-example/blob/master/WORKSPACE). Since the readme is out od date.

**Comment by alexeagle** [comment]
Oh, okay then, maybe it's a bug. Perhaps https://github.com/bazelbuild/rules_nodejs/issues/101 is related?
I cloned the example repo and it builds fine for me.

Platform, OS version, bazel version?

You could add debugging in https://github.com/bazelbuild/rules_nodejs/blob/master/internal/npm_install.bzl#L19 to confirm that we actually do run the npm install.

**Comment by acehko** [comment]
Yes, I think it's related.
I had node version `9.5.0` installed on my system.
When I switched to version `8.9.4` it the build works.
I think it might be related to this isssue: [bazelbuild/rules_nodejs#77](https://github.com/bazelbuild/rules_nodejs/issues/77)

**Comment by alexeagle** [comment]
Yes, thanks, that explains the problem.
