### ISSUE TITLE
Externalize concatjs

### ISSUE THREAD

**Issue by achew22** [bazelbuild/rules_typescript#164]
Currently concatjs lives in an `internal` directory. It seems that there is nothing prohibitivly internal about it except for the parent directory. Would it be possible to move concatjs up a dir into the root, or make a "go" dir at the root and put it in there? Crossing visibility always makes me a little uncomfortable

**Comment by mprobst** [comment]
What's the use case?

Andrew Z Allen <notifications@github.com> schrieb am Mo., 5. März 2018 um
08:49 Uhr:

**Comment by achew22** [comment]
​From the documentation section titled "Serving TypeScript for Development
<https://chrome.google.com/webstore/detail/chromevox/kgejglhpjiefppelpmljglcjbhoiplfn>
"

> Teach your real frontend server to serve files from Bazel's output
directory. This is not yet documented. Choose this option if you have an
existing server used in development mode, or if your requirements exceed
what the ts_devserver supports. Be careful that your development round-trip
stays fast (should be under two seconds).

It seems the majority of the logic required to teach a server how to do
this is contained in the concatjs folder and being able to import it would
be useful.

From the comment at the top of the concatjs.go
<https://github.com/bazelbuild/rules_typescript/blob/master/internal/concatjs/concatjs.go#L28>
file:

"""
// Example usage:
// http.Handle("/app_combined.js",
// concatjs.ServeConcatenatedJS("my/app/web_srcs.MF", ".", [], [], nil))
"""

**Comment by alexeagle** [comment]
To be clear, you can already do this today, right? but you have to import from the /internal package?
Or does the go third_party vendoring require that it be in some predictable path?

**Comment by achew22** [comment]
My understanding of `internal` packages is that they are equivalent to `//visibility:private` (and transposed as such by gazelle). Is this a misunderstanding on my part?

https://golang.org/doc/go1.4#internalpackages

**Comment by alexeagle** [comment]
The actual visibility is here: 
https://github.com/bazelbuild/rules_typescript/blob/master/internal/concatjs/BUILD#L3
(we don't use gazelle here because this is synced from google3)

I agree this package should be reusable in other Go devservers.

**Comment by achew22** [comment]
Just to confirm this, it is 100% not possible to use this outside of the rules_typescript repo.

Here is the error when I attempt to load it via your BUILD files.

```
ERROR: /home/achew22/go/src/REDACTED/BUILD:19:1: Target '@com_github_bazelbuild_rules_typescript//internal/concatjs:concatjs' is not visible from target '//REDACTED/server:go_default_library'. Check the visibility declaration of the former target if you think the dependency is legitimate
```

When I try to load it with `build_file_generation = "on"` (which replaces the generated BUILD files) and uses Gazelle to generate new ones, I get the error:

```
ERROR: /home/achew22/go/src/REDACTED/BUILD:19:1: Target '@com_github_bazelbuild_rules_typescript//internal/concatjs:go_default_library' is not visible from target '//REDACTED/server:go_default_library'. Check the visibility declaration of the former target if you think the dependency is legitimate
```

WRT how to keep Google3's BUILD files compatible with the OSS stuff, I think I have a theory. I'll TAL @ it and follow up over email.
