### ISSUE TITLE
does pinto_library exists on OpenSource version?

### ISSUE THREAD

**Issue by javatlacati** [bazelbuild/rules_typescript#169]
referenced here:

https://github.com/bazelbuild/rules_typescript/blob/master/internal/common/compilation.bzl#L73

**Comment by javatlacati** [comment]
Also leaked [at IntelliJ plugin I think](https://github.com/bazelbuild/intellij/blob/bc2cf6e2f7ad2a24db35d0c36438dc301936669a/base/src/com/google/idea/blaze/base/model/primitives/Kind.java#L85)

**Comment by alexeagle** [comment]
Not planning to do anything about the word "pinto" leaking.
