### ISSUE TITLE
Documentation improvement suggestions

### ISSUE THREAD

**Issue by fwouts** [bazelbuild/rules_typescript#173]
Thank you for bringing us TypeScript support on Bazel. Very exciting!

Here's some feedback on the documentation which I hope will be helpful:
1. It looks like you're meant to have `package.json` and `node_modules/` at the root of your workspace, and it's not possible to specify more granular package dependencies for each `ts_library`. Or maybe I misunderstood. It would be worth clarifying exactly how you're meant to manage NPM dependencies when working on a large-scale project.
2. I couldn't find documentation explaining how to import a module from another workspace (I assume this would get tricky in regards to NPM dependencies).
3. It would be useful to add documentation for compiling a JavaScript bundle without starting a devserver. I discovered that it was possible [using `nodejs_binary`](https://github.com/bazelbuild/rules_typescript/blob/master/examples/some_module/BUILD.bazel) after digging through each example in depth.
4. In my case, the devserver failed because the default port wasn't allocated. It may be useful to document how to override the port (`bazel run //path/to/devserver -- --port=8090`).

I'd happily send a PR for these, only I barely understand how it all works. Feel free to close this issue if these topics are already covered elsewhere.

Cheers!

**Comment by alexeagle** [comment]
1. You can make as many `filegroup` targets as you like that represent groups of node modules. For example, https://github.com/angular/angular/commit/4f609687044a5b7cd15f796bce948e9385b70f7a#diff-2e36a6bb46f11de1a042aa34d7106bf1 shows a compiletime deps which is different from runtime deps. Note that these don't compose - for a given compilation/binary execution all the needed node modules have to be in the same filegroup.

What do you mean by "compiling a JavaScript bundle without starting a devserver"? Do you mean running the typescript compiler to produce JS? Producing a bundle like with https://bazelbuild.github.io/rules_nodejs/rollup/rollup_bundle.html#rollup_bundle

**Comment by fwouts** [comment]
Thanks Alex.

1. Ideally, I'd like to be able to specify external dependencies on a per-target basis, like you would in other languages supported like Bazel (e.g. `deps = ["//third_party/some/library"]` in Java). However I've since found out that this is by design and [documented](https://github.com/bazelbuild/rules_nodejs#design) in the Node repo. I'm used to the convenience of Bazel being both a build tool and a package manager, and didn't realise this wasn't the case here. Maybe linking to the Node rules readme would help, for those of us who aren't aware of the relationship between the TypeScript rules and the Node rules? Merging the repos (#133) would work too.

Yes, the `rollup_bundle` rule was what I was looking for. Cheers!

**Comment by alexeagle** [comment]
I've been meaning to try out rules_typescript with pubref/rules_node or dropbox/rules_node - both of those have deps on individual node_modules which as you point out is more idiomatic for Bazel. In theory we ought to be able to make that work, then you'd have that option as well.

**Comment by alexeagle** [comment]
I don't think we'll ever include this in our scope. If you want Bazel to be the package manager, you should use someone else's rule set.
