### ISSUE TITLE
Add a ts_devserver rule

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_typescript#19]
This requires a few things:

- Each ts_library compilation should produce the _es5_manifest.MF file that lists the topo-sorted module graph observed in this compilation. We should decompose this out of tsickle where it currently lives, and put in a TS transformer. here's a pointer: https://github.com/angular/tsickle/blob/5ac90e8499acebbe828aa1314fcf4eb86dd6b08f/src/es5processor.ts#L113 - I am hoping @lucassloan can help
(note: we do this per-library to avoid re-parsing files when we get a request)
- we need to open-source the Go implementation of our devserver and concatjs programs. Maybe @mprobst would like to get this started?
- need the Bazel rule that runs the devserver
- test that it works with ibazel

/cc @vsavkin

**Comment by evmar** [comment]
Assign this one to me.

**Comment by alexeagle** [comment]
@evmar check your mail for an invite to be a collaborator on this repo

**Comment by alexeagle** [comment]
I have a simple and fast prototype for this:
https://github.com/alexeagle/angular-bazel-example/blob/98af46d27bab378e4ed5f14799c80578f0287d55/airplane/BUILD.bazel#L31

**Comment by alexeagle** [comment]
Fixed by https://github.com/bazelbuild/rules_typescript/pull/63
