### ISSUE TITLE
ts_declaration is not exposed

### ISSUE THREAD

**Issue by fortuna** [bazelbuild/rules_typescript#2]
I couldn't figure out how to specify dependencies on `.d.ts` files.
I can't create a library of .d.ts files with `ts_library`. I tried creating a `filegroup` and adding as `data` or `deps` but it didn't work.

It seems that we need `ts_declaration`, but that's not available publicly. Is there a workaround?
It would be great to add an example that used `.d.ts` files.

**Comment by alexeagle** [comment]
Update: we have some discussion ongoing about whether it even makes sense to have separate `ts_declaration` rule - it's only for expressing intent. We could just permit `.d.ts` files in the `srcs[]` of `ts_library`...

/cc @mprobst @evmar

**Comment by fortuna** [comment]
FYI, this issue has not actually been solved. While the rule allows `.d.ts` files in the `srcs[]`, the file must be in the same directory, or else you get an error. Example:
```
attribute srcs: Sources must be in the same package as the ts_library rule, but //src/types:node-forge.d.ts is not in src/infrastructure.
```

The error comes from this line of code:
https://github.com/bazelbuild/rules_typescript/blob/master/internal/common/compilation.bzl#L150
