### ISSUE TITLE
Better documentation when a transitive dependency is added

### ISSUE THREAD

**Issue by prestonvanloon** [bazelbuild/rules_typescript#202]
ERROR: Failed to load Skylark extension '@io_bazel_rules_webtesting//web:web.bzl'.
It usually happens when the repository is not defined prior to being used.
Maybe repository 'io_bazel_rules_webtesting' was defined later in your WORKSPACE file?

Do I need `io_bazel_rules_webtesting`? It's not in README or otherwise indicated from what I could tell.

**Comment by alexeagle** [comment]
https://github.com/angular/angular/pull/23828 is an example of the update needed. Yes, we now have a transitive dependency on rules_webtesting.

**Comment by alexeagle** [comment]
Hmm @gregmagolan we should think of a way to help users get the right `WORKSPACE` contents. Any ideas? `postinstall` npm hook? Make the README in this repo generated from a working example that's verified on CI?

**Comment by gregmagolan** [comment]
@alexeagle I think that your https://github.com/bazelbuild/rules_typescript/pull/256 is sufficient and self-documenting for what the transitive deps are for rules_typescript on top of including BREAKING CHANGE notes when new dependencies are added.

Similarly, https://github.com/bazelbuild/rules_nodejs/commit/e4270286273fab1e96f45e5001b72feef7db1af7 and https://github.com/bazelbuild/rules_nodejs/commit/d71f5d081732c4b63081378cf1a1d50ea25ea8ff for rules_nodejs.

@prestonvanloon See https://github.com/alexeagle/angular-bazel-example/blob/master/WORKSPACE#L37 for how to use the `rules_typescript_dependencies()` function.
