### ISSUE TITLE
ts_web_test_suite doesn't work with sauce

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_typescript#205]
I should be able to do a `ts_web_test_suite(browsers=["@io_bazel_rules_webtesting//browsers/sauce:chrome-win10"])`

but it fails, not surprising since it seems that the template `karma.conf.js` has special cases for mapping `CHROMIUM` and `FIREFOX` keys from the `WEB_TEST_METADATA`.

Can it map the web_test_metadata more transparently to karma?
I can look up what we do in google-internal if that's helpful.

/cc @joshbruning @zzo as FYI

**Comment by gregmagolan** [comment]
I think the https://github.com/karma-runner/karma-sauce-launcher plugin is required and the karma config updated to handle the configuration when a sauce labs browser is setup.

**Comment by gregmagolan** [comment]
Resolved with #208 (https://github.com/bazelbuild/rules_typescript/commit/da56a5d2f7bc36c7adffa2dcc9a5711442582c46)
