### ISSUE TITLE
amd-module definition duplicated twice at the top of index.ts

### ISSUE THREAD

**Issue by kylecannon** [bazelbuild/rules_typescript#225]
I'm not sure whats causing this, but we have a very simple file:

```ts
export * from './src/webpack.config';
```

and when bazel builds it, I get the following error:

```
Error at node_modules/@redacted-webpack/angular/src/webpack.config.d.ts:2:1: An AMD module cannot have multiple name assignments.
Error at node_modules/@redacted-webpack/angular/testing/index.d.ts:2:1: An AMD module cannot have multiple name assignments.
```

The output for the files are as follows in the bazel-bin folder (notice the double amd-module declaration)

```ts
/// <amd-module name="@redacted-webpack/angular" />
/// <amd-module name="@redacted-webpack/angular" />
export * from './src/webpack.config';
```

This seems to happen with every single outputted `.d.ts` file.

Here is the `BUILD` file

```
package(default_visibility = ["//visibility:public"])

load("@build_bazel_rules_typescript//:defs.bzl", "ts_library")
load("@build_bazel_rules_nodejs//:defs.bzl", "npm_package")

ts_library(
    name = "lib",
    srcs = glob([
        "index.ts",
        "src/**/*.ts",
        "testing/**/*.ts",
    ]),
    module_name = "@redacted-webpack/angular",
    tsconfig = "//:tsconfig.json",
)

npm_package(
    name = "npm",
    srcs = glob([
        "package.json",
        "src/**/*.js",
    ]),
    deps = [":lib"],
)
```

Running v0.15

**Comment by Toxicable** [comment]
This is the line doing that: https://github.com/bazelbuild/rules_typescript/blob/c7b6880767eaae44d8777a7a1b137de92b8fd4d9/internal/tsc_wrapped/compiler_host.ts#L381
This is the related issue in TS that was that reason for needing the work around.
https://github.com/Microsoft/TypeScript/issues/18648
Should be fixed by: https://github.com/bazelbuild/rules_typescript/pull/226

**Comment by kylecannon** [comment]
Fantastic, I was just a day early on finding this. Thanks @Toxicable.

**Comment by alexeagle** [comment]
should be fixed in next release
