### ISSUE TITLE
bazelOptions are not inherited from extended tsconfigs

### ISSUE THREAD

**Issue by JaredNeil** [bazelbuild/rules_typescript#245]
[`tsconfig.ts`](https://github.com/bazelbuild/rules_typescript/blob/master/internal/tsc_wrapped/tsconfig.ts#L276) parses the `bazelOptions` from the tsconfig provided by the user, but not recursively from tsconfigs that it `extends`.

**Comment by alexeagle** [comment]
Fix is in #265

**Comment by alexeagle** [comment]
was fixed I believe
