### ISSUE TITLE
devserver does not work on Windows

### ISSUE THREAD

**Issue by filipesilva** [bazelbuild/rules_typescript#270]
Running `//devserver/devserver:go_default_test` under windows fails with the following test log:
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //devserver/devserver:go_default_test
-----------------------------------------------------------------------------
2018/09/14 15:48:33 could not change to test directory: chdir C:\users\kamik\_bazel_kamik\5c2rzegw\execroot\build_bazel_rules_typescript\bazel-out\x64_windows-fastbuild\bin\devserver\devserver\windows_amd64_stripped\go_default_test.exe.runfiles\build_bazel_rules_typescript\devserver\devserver: The system cannot find the path specified.
```

Looking at the end of the missing path (`go_default_test.exe.runfiles\build_bazel_rules_typescript\devserver\devserver`) hints towards `rules_go` not reading the runfiles manifest on Windows.

`//devserver/concatjs:go_default_test` and `//ts_auto_deps/analyze:go_default_test` also exhibit this error.

**Comment by alexeagle** [comment]
fixed in 4532a4a
