### ISSUE TITLE
how to load npm module from ts_devserver with fine grained deps

### ISSUE THREAD

**Issue by wayou** [bazelbuild/rules_typescript#310]
say we setup the project like this:

```bash
.
├── BUILD.bazel
├── WORKSPACE
├── package.json
├── src
│   ├── BUILD.bazel
│   ├── index.html
│   └── index.ts
├── tsconfig.json
└── yarn.lock
```

src/BUILD.bazel:

```python
package(default_visibility = ["//visibility:public"])

load("@build_bazel_rules_typescript//:defs.bzl", "ts_devserver", "ts_library")

ts_library(
    name = "ts_example",
    srcs = [
        "index.ts",
    ],
    deps = [
        "@npm//@types/lodash",
        "@npm//lodash",
    ],
)

ts_devserver(
    name = "devserver",
    entry_module = "bazel_ts_example/src/index",
    serving_path = "/bundle.min.js",
    static_files = [
        "index.html",
    ],
    deps = [
        ":ts_example",
    ],
)
```

src/index.ts

```typescript
import { sample } from "lodash";
document.body.innerHTML = sample(['foo','bar'])!;
```

the `bundle.min.js` requests `lodash` from the server root path which will certainly fail.

<img width="678" alt="qq20181019-154328 2x" src="https://user-images.githubusercontent.com/3783096/47204449-e76cab00-d3b5-11e8-8b4d-d35e8aeeab44.png">

**Comment by solomatov** [comment]
I have the same problem. Please, do something about it.

**Comment by wayou** [comment]
> @wayou Did you get it to work?
not yet.

**Comment by alexeagle** [comment]
Just need to include target `@npm//node_modules/lodash:lodash__umd` in the `ts_devserver#deps`

Behind the scenes, this uses browserify to create an UMD version of lodash which can be bundled in along with your sources.

**Comment by alexeagle** [comment]
https://github.com/alexeagle/repro_ts_310 shows how it works

**Comment by solomatov** [comment]
Thank you very much. It's a super important issue for me.
