### ISSUE TITLE
Warn the user when an option in tsconfig is ignored

### ISSUE THREAD

**Issue by fortuna** [bazelbuild/rules_typescript#34]
In my tsconfig I have `target: "es6"`. However, on `bazel build src/shadowbox:model`, bazel is outputting a `model_es5_tsconfig.json` file with contents:
```
{
  "compilerOptions": {
    "target": "es5",
    "downlevelIteration": true,
    "skipDefaultLibCheck": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "outDir": "../../../../../../bazel-out/local-fastbuild/bin",
    "rootDir": "../../../../../..",
    "rootDirs": [
      "../../../../../..",
      "../../../../../../bazel-out/local-fastbuild/genfiles",
      "../../../../../../bazel-out/local-fastbuild/bin"
    ],
    "baseUrl": "../../../../../..",
    "paths": {
      "*": [
        "./*",
        "bazel-out/local-fastbuild/genfiles/*",
        "bazel-out/local-fastbuild/bin/*"
      ]
    },
    "preserveConstEnums": false,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "jsx": "react",
    "jsxFactory": "React.createElement",
    "noEmitOnError": false,
    "declaration": true,
    "stripInternal": true,
    "inlineSourceMap": true,
    "inlineSources": true,
    "sourceMap": false
  },
  "bazelOptions": {
    "workspaceName": "__main__",
    "target": "//src/shadowbox/model:model",
    "tsickle": false,
    "tsickleGenerateExterns": true,
    "tsickleExternsPath": "",
    "untyped": true,
    "typeBlackListPaths": [],
    "es5Mode": true,
    "manifest": "bazel-out/local-fastbuild/bin/src/shadowbox/model/model.es5.MF",
    "compilationTargetSrc": [
      "src/shadowbox/model/metrics.ts",
      "src/shadowbox/model/shadowsocks_server.ts",
      "src/shadowbox/model/user.ts"
    ],
    "disableStrictDeps": false,
    "allowedStrictDeps": [],
    "enableConformance": false,
    "nodeModulesPrefix": "node_modules"
  },
  "files": [
    "../../../../../../src/shadowbox/model/metrics.ts",
    "../../../../../../src/shadowbox/model/shadowsocks_server.ts",
    "../../../../../../src/shadowbox/model/user.ts"
  ],
  "compileOnSave": false,
  "extends": "../../../../../../src/shadowbox/tsconfig"
}
```

And I get compilation errors:
```
$ bazel build src/shadowbox/model:model
INFO: Found 1 target...
ERROR: /Users/fortuna/firehook/uproxy-cloud-install/src/shadowbox/model/BUILD:5:1: Compiling TypeScript (devmode) //src/shadowbox/model:model failed (Exit 1).
src/shadowbox/model/user.ts(35,16): error TS2304: Cannot find name 'IterableIterator'.
src/shadowbox/model/metrics.ts(17,104): error TS2304: Cannot find name 'Map'.
src/shadowbox/model/metrics.ts(35,26): error TS2304: Cannot find name 'Set'.
```

Which makes me believe it's ignoring the ES6 target and using ES5 instead.

**Comment by alexeagle** [comment]
To get ES6 outputs, downstream rules must request them from the `typescript` provider. Follow https://github.com/bazelbuild/rules_typescript/issues/21

I'll re-purpose this issue to give a more clear indication that the setting from your tsconfig file is overridden (that option is one controlled by Bazel)

**Comment by yohcop** [comment]
Is the `compilerOptions.lib` array completely discarded? I can't seem to impact it, even by changing my `tsconfig.json` file (or, as I was trying to dig deeper, the `tsconfig.json` of `tsc_wrapped`.

Asking here, because it is related to this issue. In fact, I feel like @fortuna 's error could be solved with the right set of libs added, but I'm not sure.

Adding my libs to the `compiler_options` dictionary in `tsconfig.bzl` does solve my issue, but obviously not a real solution :)

**Comment by yohcop** [comment]
Ah, nevermind. It's late, I'm starting to get tired. The generated tsconfig extends mine, so it should have my lib in it. Or should it? It's still a mystery why they don't seem to work if I add "esnext" to my tsconfig.json libs.

I get those errors: `error TS2304: Cannot find name AsyncIterator.`. If I add "esnext" to `tsconfig.bzl`, it works...

**Comment by alexeagle** [comment]
First step to debug this is to add the `-s` option to bazel build. It will
echo the compiler commands which includes the path to the generated
tsconfig.

**Comment by yohcop** [comment]
Ok, After more investigation, the problem was related to tsconfig.json, but not exactly what I thought. I created #92.
