### ISSUE TITLE
com_github_kylelemons_godebug and com_github_mattn_go_isatty should be loaded with _maybe helper

### ISSUE THREAD

**Issue by ashi009** [bazelbuild/rules_typescript#341]
com_github_kylelemons_godebug and com_github_mattn_go_isatty are declared directly without using _maybe helper, which may override previously defined go_repository.

(Somehow go_repository with the same name can now be redeclared. Possibly a rules_go bug?)

**Comment by ashi009** [comment]
After reading https://github.com/bazelbuild/rules_go/issues/749 this seems reasonable. However, this bazel feature should be documented in big red bold text.

**Comment by ashi009** [comment]
Reopening this given the [comment](https://github.com/bazelbuild/bazel/issues/6864#issuecomment-448619993) by @dslomov, this is a bug and it will break some day.

**Comment by alexeagle** [comment]
I think this doesn't matter anymore now that we ship pre-compiled Go binaries. Building rules_typescript from source should be an unusual edge case now
