### ISSUE TITLE
Lacking documentation of ts_library parameters

### ISSUE THREAD

**Issue by fortuna** [bazelbuild/rules_typescript#35]
The rule `ts_library` has a few parameters that are not documented in the README file: `module_name`, `module_root`, `tsc`, `runtime`.

They sound useful and it would be nice to have them explained in the documentation.

**Comment by alexeagle** [comment]
we generate documentation from the starlark code now
https://github.com/bazelbuild/rules_nodejs/blob/master/docs/TypeScript.md
