### ISSUE TITLE
is neither a TypeScript nor a JS producing rule.

### ISSUE THREAD

**Issue by clanstyles** [bazelbuild/rules_typescript#375]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: ts_library

### Is this a regression?

 Yes, the previous version in which this bug was not present was: unsure

### Description

 A clear and concise description of the problem:
We're using https://github.com/stackb/rules_proto to generate protobuf clients. When we use commonjs_grpc_compile to generate our gRPC code, your library says the output isn't going to be JS

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>

  </code>
</pre>

**Output of `bazel version`:**

<pre>
  <code>

  </code>
</pre>

**Rules version (SHA):**

<pre>
  <code>

  </code>
</pre>

**Anything else relevant?**

**Comment by pcj** [comment]
@clanstyles hard to say without more information.  One thing to recall is that the `commonjs_grpc_compile` rule will generate source files, so the rule providing should be named in the `ts_library.srcs` attribute, not the `ts_library.deps` attribute.

**Comment by clanstyles** [comment]
I'm trying to generate with commojs_* from the stackb/ and I'm getting that.

**Comment by alexeagle** [comment]
let's roll it into #116
