### ISSUE TITLE
Setup golint in CI

### ISSUE THREAD

**Issue by mgechev** [bazelbuild/rules_typescript#383]
# 🚀 feature request

### Description

We have a lot of go code. To ensure consistency and make sure that the PRs here align with the internal code standards as closely as possible we should introduce golint.

### Describe the solution you'd like

Run golint in buildkite & CircleCI

**Comment by alexeagle** [comment]
Since this repo is piper source-of-truth, I'm concerned about setting up any tooling that disagrees with what google-internal does. I think the only benefit of linting on github is to help contributors get a PR that we don't need to fixup when we sync

**Comment by mgechev** [comment]
That's mostly to reduce the number of warnings we get internally. The code goes through golint.

**Comment by alexeagle** [comment]
We aren't actively working on the Go code here and I don't think we'll have time to set up more infra. LMK if you still want to do this
