### ISSUE TITLE
terrible error if users rules_nodejs is too old

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_typescript#40]
rules_typescript has a dependency on rules_nodejs at some version.

Due to https://github.com/bazelbuild/bazel/issues/1943
users have to specify all the tags in their WORKSPACE so they are free to pick versions that don't work.

https://github.com/bazelbuild/bazel/issues/2757#issuecomment-290448615 seems like a workaround: publish a repository_rule that installs our deps at the right tag.

**Comment by gregmagolan** [comment]
rules_typescript now checks for a minimum rules_nodejs version and it also provides a rules_typescript_dependencies() repository rule so that the correct rules_nodejs version will be installed in a user's repo by default
