### ISSUE TITLE
Downloading rules_nodejs 0.32.0 fails

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/rules_typescript#459]
Probably caused by https://github.com/bazelbuild/rules_typescript/commit/0efe29e17efee84f722326378b7585dac4f48784

https://buildkite.com/bazel/rules-typescript-typescript/builds/1535#_

```

ERROR: An error occurred during the fetch of repository 'build_bazel_rules_nodejs':
--
  | java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_nodejs/releases/download/0.32.0/rules_nodejs-0.32.0.tar.gz] to /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/build_bazel_rules_nodejs/rules_nodejs-0.32.0.tar.gz: GET returned 404 Not Found


```

**Comment by meteorcloudy** [comment]
@gregmagolan

**Comment by meteorcloudy** [comment]
This is also failing for rules_sass for the same reason

**Comment by sgammon** [comment]
https://github.com/bazelbuild/rules_nodejs/archive/0.32.0.tar.gz works still, fyi

**Comment by meteorcloudy** [comment]
@gregmagolan @alexeagle 
This has been failing on Bazel CI for many days. Is anyone looking into a fix?
https://buildkite.com/bazel/rules-typescript-typescript/builds/1538

**Comment by Toxicable** [comment]
This is the wrong repo for this issue, it should be in `rules_nodejs`
as for your issue: can you change to `0.32.2`

**Comment by meteorcloudy** [comment]
I sent https://github.com/bazelbuild/rules_typescript/pull/460 to fix

**Comment by gregmagolan** [comment]
> I sent #460 to fix

Thanks @meteorcloudy. That release archive was taken down unintentionally when updating the release notes.

@alexeagle is back next week and can get definitely get this merged. @kyliau, are you able to get this merged today or tomorrow so green up Bazel's CI? Also https://github.com/bazelbuild/rules_sass/pull/92 for the same reason.

**Comment by gregmagolan** [comment]
@meteorcloudy I regenerated the archive locally and ended up with the same sha256 (as it should be) so I put it back up on GitHub. https://github.com/bazelbuild/rules_nodejs/releases/download/0.32.0/rules_nodejs-0.32.0.tar.gz. Closing this although it won't hurt to land #460 and https://github.com/bazelbuild/rules_sass/pull/92 to get those repos up to the latest patch.

**Comment by meteorcloudy** [comment]
Thanks for the fix!
