### ISSUE TITLE
Add ability to retrieve TS source files from ts_library and it's deps

### ISSUE THREAD

**Issue by a-ignatov-parc** [bazelbuild/rules_typescript#462]
# 🚀 feature request

### Relevant Rules

- `ts_library` in `rules_nodejs`
- `ts_proto_library` in `rules_nodejs`
- `node_module_library` in `rules_nodejs` (?)

### Description

Add ability to retrieve TS sources from `ts_library` in case if a developer wants to use custom transpiler in addition to `devmode` that is used for type checking and nodejs interop.

For example, we use webpack for production builds and dev-server and now we forced to compile TS twice in `devmode` and `prodmode` because we need `esnext` modules for dynamic imports and proper dependency resolution. Moreover, we could use `ts-loader` just for the transpilation and improve build times.

### Describe the solution you'd like

Extend ts provider with additional `ts_sources` and `transitive_ts_sources`

### Describe alternatives you've considered

Implement custom `ts_library` that will use `compile_ts` and override `compile_action` attr. However, this solution introduces a lot of overhead because the default `compile_action` and `devmode_compile_action` implementations are private and have a lot of specific things like `tsickle_externs`.

**Comment by alexeagle** [comment]
The typical way to do another action on the original TS files is to use an aspect.see https://docs.bazel.build/versions/master/skylark/aspects.html

This lets you write some bazel plugin code that visits the original `ts_library` targets but do something different with their inputs, and make whatever new outputs you like.

Angular needed to do exactly this: they need a third "flavor" of javascript output from ts_library so they replay the original action with a modified tsconfig
https://github.com/angular/angular/blob/master/packages/bazel/src/esm5.bzl

but you could do anything you want given the original .ts files and the tsconfig.json that the original action used.

**Comment by a-ignatov-parc** [comment]
@alexeagle thanks! Sounds like exactly what I need. I'll give it a try 👍

**Comment by a-ignatov-parc** [comment]
I was able to collect all source files from `ts_library` with aspect, so there is no need in this feature request anymore.
