### ISSUE TITLE
Bad error message when installed typescript version isn't compatible with tooling

### ISSUE THREAD

**Issue by KyleLehtinenDev** [bazelbuild/rules_typescript#48]
I came across the following error when attempting to build the example with version 0.2.2:

```
ERROR: /private/var/tmp/_bazel_kylelehtinen/44fb04a4c0d5b92efea3ee928a865cfc/external/build_bazel_rules_typescript/internal/tsc
_wrapped/BUILD.bazel:26:1: Compiling TypeScript (devmode) @build_bazel_rules_typescript//internal/tsc_wrapped:tsc_wrapped failed (Exit 2).
external/build_bazel_rules_typescript/internal/tsc_wrapped/compiler_host.ts(361,5): error TS2322: Type 'string | undefined' isnot assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.

```
Line 361 in compiler_host.ts invokes the typescript method 'readFile' which can return undefined, but the wrapper method here is typed only to return a string. When I updated the return type to include string or undefined the error went away and my sample typescript files were successfully built/transpiled. 

I don't know much beyond that but thought I'd bring it up.

**Comment by Quramy** [comment]
@KyleLehtinenDev Using `typescript@2.4.2` solves this issue.
