### ISSUE TITLE
ts_library cannot depend on a genrule

### ISSUE THREAD

**Issue by fortuna** [bazelbuild/rules_typescript#5]
This minimal example fails:
```python
genrule(
  name = "foo_ts",
  outs = ["foo.ts"],
  cmd = "echo 'export const FOO = 1;' > $@",
)

ts_library(
  name = "foo",
  srcs = [":foo.ts"],
)
```

With error:
```
$ bazel build src/web_app:foo
INFO: Found 1 target...
ERROR: /usr/local/google/home/fortuna/firehook/uproxy-cloud-install/src/web_app/BUILD:37:1: output 'src/web_app/foo.js' was not created.
ERROR: /usr/local/google/home/fortuna/firehook/uproxy-cloud-install/src/web_app/BUILD:37:1: output 'src/web_app/foo.d.ts' was not created.
ERROR: /usr/local/google/home/fortuna/firehook/uproxy-cloud-install/src/web_app/BUILD:37:1: not all outputs were created or valid.
Target //src/web_app:foo failed to build
```

It seems the bazel rule identified the input somehow, but I think it didn't make it all the way to tsc.

**Comment by fortuna** [comment]
I collected more data. This is the command run:
```
$ bazel build src/web_app:foo -s
INFO: Found 1 target...
>>>>> # //src/web_app:foo [action 'Generating src/web_app/foo.js']
(cd /usr/local/google/home/fortuna/.cache/bazel/_bazel_fortuna/c137b717646fb7493bea3ee2bfe4288b/execroot/uproxy-cloud-install && \
  exec env - \
  bazel-out/host/bin/external/io_bazel_rules_typescript/internal/tsc_wrapped -p bazel-out/local-fastbuild/bin/src/web_app/foo_es5_tsconfig.json)
```

And `foo_es5_tsconfig.json` looks like this:
```
  "compilerOptions": {
    "outDir": "../../../../../bazel-out/local-fastbuild/bin",
    "rootDir": "../../../../..",
    "rootDirs": [
      "../../../../..",
      "../../../../../bazel-out/local-fastbuild/genfiles",
      "../../../../../bazel-out/local-fastbuild/bin"
    ],
    "baseUrl": "../../../../..",
```

The problem is that `foo.d.ts` and `foo.js` are being output to `bazel-out/local-fastbuild/bin/bazel-out/local-fastbuild/genfiles/src/web_app/` rather than `bazel-out/local-fastbuild/bin/src/web_app/`. Something is wrong with the `tsconfig.json`.

**Comment by fortuna** [comment]
@alexeagle : FYI

**Comment by alexeagle** [comment]
Yes, thanks for filing, I'm aware of this.

Fundamentally, TypeScript does not support what we want. See https://github.com/Microsoft/TypeScript/issues/8245

The solution is to stop calling `tsc` but instead introduce our own compiler program. This is needed for other things anyway (running as a bazel worker, reducing file stats by only reading declared action inputs, adding tsickle, etc)

**Comment by fortuna** [comment]
What if we create a symlink tree under a single directory before calling the compiler? Maybe something similar to runfiles: https://bazel.build/versions/master/docs/skylark/rules.html#runfiles

**Comment by alexeagle** [comment]
I think we should have the same solution to this problem that google uses
internally. Also everything is easier to debug if we keep path handling
consistent, so inputs should never relocate.

**Comment by fortuna** [comment]
Any estimate on when we could have this fix available? I believe this issue and https://github.com/bazelbuild/rules_typescript/issues/2 are the last ones preventing us from adopting bazel.
