### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by appsforartists** [bazelbuild/rules_typescript#50]
The documented configuration (in README) will generate `.js` and `.d.ts` files in `$WORKSPACE/bazel-bin/`.  This is a good first step for applications, but what about for modules that will be published to npm - how does rules_typescript fit in to that workflow?

One possibility is that `ts_library` could copy any `package.json`s it finds in `srcs` to `bazel-bin` alongside the built files.  Then, an author could do something like

```bash
cd bazel-bin/packages/my-library/
yarn publish
```

That could probably be wrapped in its own bazel rule/command, but 👶 👣 .

**Comment by alexeagle** [comment]
See https://github.com/angular/tsickle/pull/623 as one example, just put bazel-bin path in the tsconfig and publish from the project dir

**Comment by alexeagle** [comment]
the `npm_package` and `web_package` rules should satisfy this use case.
