### ISSUE TITLE
Investigate using rollup in devmode

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_typescript#60]
Currently our prototype uses "concatjs" which bundles by simply concatenating files wrapped in eval().
However it requires we use a module format that doesn't depend on path information, which is "named AMD". This format is unusual, and if we do this it means our dependencies like rxjs have to do it too (if we want them inside the bundle)

@tbosch pointed out that we have to escape some characters in the input. Currently we do this with `JSON.stringify` although it could be much faster in go:
```
for _, b := range contents {
		switch b {
		case '\n':
			if _, err := out.Write([]byte("\\n")); err != nil {
				return err
			}
		case '\r':
			if _, err := out.Write([]byte("\\r")); err != nil {
				return err
			}
		case '\\', '\'':
			if _, err := out.Write([]byte{'\\'}); err != nil {
				return err
			}
			fallthrough
		default:
			if _, err := out.Write([]byte{b}); err != nil {
				return err
			}
		}
	}
```

In theory, rollup could also be fast, and it would let us accept commonjs inputs which is more normal.

**Comment by alexeagle** [comment]
@gregmagolan and I investigated a bit.

Even with only 1000 ES6/ESM input .js files, Rollup takes nearly 3s on my fast workstation.
https://github.com/rollup/rollup/issues/191#issuecomment-224986002 suggests that the watch mode is kind of efficient, but not as efficient as possible. Changing one of the 1000 input files, the watch mode still takes 2.2s. So it doesn't seem that watch mode is sufficiently incremental for us to use at large scale. With 10,000 input .js files, the incremental re-build after one file changed is 3m 12s!

**Comment by alexeagle** [comment]
Unless someone wants to dive into the more difficult incremental mode for rollup mentioned in that comment above, it seems clear that this isn't feasible for us.

**Comment by Globegitter** [comment]
@alexeagle one tool I have been playing around with and that seems pretty promising is pax: https://github.com/nathan/pax, it supports es6 modules, commonjs and node_module resolution and nothing else. On my tests it has worked really fast - not sure how fast it would be with 10k files, that would be interesting indedd. The other issue I ran into, one can not specify custom paths to load modules, so I ran into issues, see: https://github.com/bazelbuild/bazel/issues/5630

But that might be more easy to implement on the pax side (or see if the author would be willing to put some working into this), than try improve rollup performance.

**Comment by alexeagle** [comment]
We are relying on rollup to do fancy stuff like smart code splitting with common chunks. It's going to be a key part of our delivery strategy for Angular Elements. I doubt another bundler could implement that feature, it's very tricky.
Certainly you could write a pax_bundle rule and see what mileage you get.
