### ISSUE TITLE
Demonstrate usage of protocol buffers

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_typescript#61]
Should have type-safe access to generated protos.

We could use this in our own repo: currently proto objects are type `any`, eg
https://github.com/bazelbuild/rules_typescript/blob/64567904e3648b728f356057bdf6d0ed603be388/internal/tsc_wrapped/worker.ts#L26

https://github.com/dcodeIO/ProtoBuf.js/#usage-with-typescript seems like the obvious `.d.ts` code generator to use. This also implies that the library must use the protobuf.js generated runtime.

/cc @jart

**Comment by achew22** [comment]
Having written a few protoc plugins, you might consider writing your own. It will provide you a lot more control and have relatively few downsides other than taking an afternoon. It also has the fun bootstrapping problem of writing a proto parser that uses its own output to parse the protos. What's more meta than that!

**Comment by pshields** [comment]
Another option might be the `closure_js_proto_library` rule from `rules_closure`. I logged #116 since as far as I can tell it is already generating a Closure-annotated .js output, but I think the output may not be in the place that ts_library expects.

**Comment by alexeagle** [comment]
As mentioned in the other thread - producing closure-annotated .js isn't useful for ts_library since we don't want to introduce the complexity of converting closure JS signatures to `.d.ts` files.

**Comment by SirVer** [comment]
This is exciting progress!

**Comment by alexeagle** [comment]
Documentation published at http://tsetse.info/api
