### ISSUE TITLE
starting from 0.4, users need tsutils in their node modules

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_typescript#88]
Failure looks like
```
ERROR: /usr/local/google/home/alexeagle/.cache/bazel/_bazel_alexeagle/5c094f47f582dc47fc598194e749d5c0/external/build_bazel_rules_typescript/internal/tsetse/rules/BUILD:19:1: Compiling TypeScript (devmode) @build_bazel_rules_typescript//internal/tsetse/rules:rules failed (Exit 2)
external/build_bazel_rules_typescript/internal/tsetse/rules/check_return_value_rule.ts(8,26): error TS2307: Cannot find module 'tsutils'.
external/build_bazel_rules_typescript/internal/tsetse/rules/check_return_value_rule.ts(108,40): error TS2339: Property 'name' does not exist on type 'LeftHandSideExpression'.
external/build_bazel_rules_typescript/internal/tsetse/rules/check_return_value_rule.ts(111,42): error TS2339: Property 'argumentExpression' does not exist on type 'LeftHandSideExpression'.
INFO: Elapsed time: 12.840s, Critical Path: 3.29s
FAILED: Build did NOT complete successfully
```

This happens because the node module resolution fails inside the TypeScript compiler. Digging deeper, with the debug flag flipped in `internal/common/tsconfig.bzl`, we see where TypeScript looked for `tsutils`

```
Directory '/execroot/angular_src/external/build_bazel_rules_typescript/node_modules' does not exist, skipping all lookups in it.
Directory '/execroot/angular_src/external/node_modules' does not exist, skipping all lookups in it.
File '/execroot/angular_src/node_modules/tsutils.ts' does not exist.
File '/execroot/angular_src/node_modules/tsutils.tsx' does not exist.
File '/execroot/angular_src/node_modules/tsutils.d.ts' does not exist.
File '/execroot/angular_src/node_modules/@types/tsutils.d.ts' does not exist.
```

Some package managers (some versions of yarn?) will hoist the `tsutils` dependency all the way to the top, so the `/execroot/angular_src/node_modules/tsutils` path would have resolved. But even if that works, it's not what we want - it means we get the version installed in the users project which might not work with rules_typescript.

The path that should have located the files is `.../execroot/angular_src/external/build_bazel_rules_typescript/node_modules` but this doesn't exist on disk. First, `@build_bazel_rules_typescript//internal/tsc_wrapped:tsc` should have had a data dependency on its own node_modules:
```
# Vanilla typescript compiler: run the tsc.js binary distributed by TypeScript
nodejs_binary(
    name = "tsc",
    data = ["@//:node_modules",
     "@build_bazel_rules_typescript//:node_modules"
    ],
    entry_point = "typescript/lib/tsc.js",
    visibility = ["//internal:__subpackages__"],
)
```

By fixing that, and then uncommenting the `find` command in `rules_nodejs/internal/node_launcher.sh` we see the actual layout on disk was
```
/execroot/angular_src/bazel-out/host/bin/external/build_bazel_rules_typescript/internal/tsc_wrapped/tsc.runfiles/build_bazel_rules_typescript/node_modules/tsutils
/execroot/angular_src/bazel-out/host/bin/external/build_bazel_rules_typescript/internal/tsc_wrapped/tsc.runfiles/angular_src/external/build_bazel_rules_typescript/node_modules/tsutils
```

**Comment by alexeagle** [comment]
Not fixed, still see this problem in Angular:
https://circleci.com/gh/angular/angular/26676?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by alexeagle** [comment]
Basically, since we now allow the user to bring their own version of typescript, we also rely on the right version of our own dependencies like tsutils.

**Comment by alexeagle** [comment]
It's more broken than described above.

I was just porting ngrx to Bazel, and decided to use a `yarn_install` for the primary node_modules - no need to `yarn install` before running `bazel build`

However, even with `--preserve-symlinks` passed to nodejs, it still goes and resolves the wrong `tsutils` location:
```
ERROR: /usr/local/google/home/alexeagle/.cache/bazel/_bazel_alexeagle/20d12b44f39647f50034d2c9a0ac2cfa/external/rxjs/BUILD.bazel:7:1: Compiling TypeScript (devmode) @rxjs//:rxjs failed (Exit 1)
RESOLVING TSUTILS FROM /usr/local/google/home/alexeagle/.cache/bazel/_bazel_alexeagle/20d12b44f39647f50034d2c9a0ac2cfa/execroot/ngrx/node_modules/tsutils/src/index.js
Compilation failed TypeError: tsutils.isExpressionValueUsed is not a function
    at Object.checkCallExpression [as handlerFunction] (/usr/local/google/home/alexeagle/.cache/bazel/_bazel_alexeagle/20d12b44f39647f50034d2c9a0ac2cfa/execroot/ngrx/bazel-out/host/bin/external/build_bazel_rules_typescript/internal/tsc_wrapped/tsc_wrapped_bin.runfiles/build_bazel_rules_typescript/internal/tsetse/rules/check_return_value_rule.js:102:25)
```

the `execroot/ngrx/node_modules` isn't an input to the action at all - but it happens that rxjs sources come from npm so they are under that directory, and we get the wrong resolution.

Perhaps we could do something like `tsc_wrapped` and just have nodejs skip any resolutions that aren't action inputs, to get a better hermeticity? @gregmagolan you just worked on that resolution logic, what do you think?

**Comment by gregmagolan** [comment]
Fixed with npm fine grained dependencies and idiomatic install of `@bazel/typescript` which have both landed. `"tsutils": "2.27.2"` is a dependency of the `@bazel/typescript` npm package and tsetse will resolve `tsutils` to `node_modules/@bazel/typescript/node_modules/tsutils` if it exists before resolving to `node_modules/tsutils`.
