### ISSUE TITLE
Strict dependency enforcement does not ignore .d.ts files from node_modules

### ISSUE THREAD

**Issue by mrmeku** [bazelbuild/rules_typescript#89]
If you want to reproduce the error clone my fork of rules_typescript at this commit https://github.com/mrmeku/rules_typescript/commit/a679bf70988afdaca9b933a900e0a3bd4d086309 and run 
bazel build //examples/angular:ts_library

This will produce the following error:
Compiling TypeScript (devmode) //examples/angular:ts_library failed (Exit 1).
examples/angular/main.ts(1,21): error TS2307: transitive dependency on ../../../../../../../Users/mrmeku/rules_typescript/examples/angular/node_modules/@types/angular/index.d.ts not allowed. Please add the BUILD target to your rule's deps.

I talked with Alex eagle a bit about this bug and here's what he has to say:
I added logging in an `else` case here:
https://github.com/bazelbuild/rules_typescript/blob/master/internal/tsc_wrapped/strict_deps.ts#L100

When we register the node_modules path with the plugin, we do a `realpath` on it to match what the TypeScript compiler should do, see comment https://github.com/bazelbuild/rules_typescript/blob/master/internal/tsc_wrapped/tsc_wrapped.ts#L103
but I found that the actual comparison was not using a `realpath`.

**Comment by mrmeku** [comment]
For my specific example, heres some useful data I've logged

declFileName: /Users/mrmeku/rules_typescript/examples/angular/node_modules/@types/angular/index.d.ts

ignoredFilesPrefix: /Users/mrmeku/rules_typescript/node_modules

For this case the bug is that my node_modules directory is not within the root of my workspace

**Comment by yohcop** [comment]
I am having the same problem, and tried naively to fix it this way:

I passed `compilerHost` to the strictDeps plugin, then called `compilerHost.realpath` on `declFileName` in `checkModuleDeps`, before the `startsWith` check on the paths, But the prefixes still don't match:

In my case, `nodeModulesPrefix` ends up being `/home/y/.cache/bazel/_bazel_y/353cc7731d9fb1ef948c81259e5d7654/bazel-sandbox/4292569854393428000/execroot/__main__/node_modules`
(i.e. something in the bazel internal directories) but `realPath(declFileName)` is something like `/d/code/fitzenith/fitzenith/web/node_modules/typestyle/lib/index.d.ts` (i.e. the path to my project source). So obviously comparing the first to the prefix of the second doesn't work.

Anyway, to try to move forward, I just disabled strict deps entirely by editing `tsc_wrapped.ts`, removing the `strictDepsPlugin.wrap()` call.

**Comment by alexeagle** [comment]
I think I need to expose an ability to disable strict deps globally for a workspace. Angular might not want it at all, at least not until we can generate the build files.

**Comment by alexeagle** [comment]
The bug is likely here:
https://github.com/bazelbuild/rules_typescript/blob/c4c065aa6a2a5c203d74a34f362270e837ab564d/internal/build_defs.bzl#L90
this should look at the ctx.attr.node_modules to get the right path.

@mrmeku are you still looking into it, do you want to try fixing that location?

**Comment by mrmeku** [comment]
I'll take a look at it tonight if you don't get to it first! My environment
is all setup to verify that the fix works so it should be pretty quick if
we understand teh problem entirely.
