### ISSUE TITLE
More convenient way to share same tsconfig for whole workspace

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_typescript#93]
Our recommendation is to do what we do at Google: a single `tsconfig.json` file for the entire Bazel workspace. This is annoying right now because every `ts_library` has to be manually configured with a `tsconfig` attribute that should always have the same value.

Option 1: in the `WORKSPACE` file, add a new repository rule like `tsconfig(default_tsconfig="//:tsconfig.json")`
Option 2: change the default for the `ts_library#tsconfig` attribute to point to some well-known location like `@//:tsconfig` and expect all users will create an `alias` or `ts_config` rule at that location

**Comment by achew22** [comment]
Is it possible to have a `ts_library` with `//a:tsconfig.json` be included in another `ts_library` with `//b:tsconfig.json` when `//a:tsconfig.json` is less restrictive than `//b:tsconfig.json`'s configuration?

**Comment by alexeagle** [comment]
There are some interactions that can cause trouble, for example if `a` is compiled without `--strictNullChecks` it can produce `a.d.ts` that is an error when consumed by `b` that does have `--strictNullChecks`. That's one of the reasons we don't recommend mixing them.

But in practice, if you use a library from npm, then the typings for that thing were probably built with different options than you have locally, so interop issues have to be dealt with sometimes.
